# .github/labeler.yml 配置
"client: web-mobile":
  - changed-files:
      - any-glob-to-any-file: ["frontend/**/*"]

"platform: backend":
  - changed-files:
      - any-glob-to-any-file:
          - "backend/**/*"
          - "!backend/v1/models/**/*"
          - "!backend/v1/schemas/**/*"
          - "!backend/v1/documentation/**/*"

# 匹配到“topic: database”
"topic: database":
  - changed-files:
      - any-glob-to-any-file:
          - "backend/v1/schemas/**/*"

# 匹配到“type: docs”
"type: docs":
  - changed-files:
      - any-glob-to-any-file:
          - "*.md"
          - "backend/v1/documentation/**/*"

# 匹配到“topic: ci-cd”
"topic: ci-cd":
  - changed-files:
      - any-glob-to-any-file:
          - ".github/workflows/*"
          - "Dockerfile"

# 匹配到“topic: config”
"topic: config":
  - changed-files:
      - any-glob-to-any-file:
          - "backend/tsconfig.json"
          - "backend/.env.example"
          - "frontend/.env.example"
          - "frontend/vite.config.ts"
          - "frontend/tsconfig.json"
          - "frontend/eslint.config.js"
          - "frontend/.eslintrc.js"
          - "frontend/vite.config.mts"
