# Install as an Nginx site on the server after downloading the certificate
# and private key for this application from the AcWing console.
server {
    listen 80;
    server_name app7592.acapp.acwing.com.cn;
    return 308 https://$host$request_uri;
}

server {
    listen 443 ssl;
    server_name app7592.acapp.acwing.com.cn;

    ssl_certificate /etc/nginx/cert/acapp.pem;
    ssl_certificate_key /etc/nginx/cert/acapp.key;
    client_max_body_size 20m;

    location ^~ /v1/ {
        proxy_pass http://127.0.0.1:1337;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    location ^~ /uploads/ {
        proxy_pass http://127.0.0.1:1337;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    location / {
        proxy_pass http://127.0.0.1:3000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}
